### ISSUE TITLE
consider candle for config stuff

### ISSUE THREAD

**Issue by MiniDigger** [MiniDigger/VoxelGamesLib#38]
https://github.com/Torchmind/Candle/

**Comment by Sxtanna** [comment]
This looks kinda ugly...

**Comment by MiniDigger** [comment]
I think that it's a good compromise between the ease of use of yaml and the simplicity of json
don't think that I will touch that any time soon, and then I will first take a look how complicated configs (like the game definitions)  look with it

**Comment by Sxtanna** [comment]
What about this? It looks cool, but it might be a bit too over complicated...
https://github.com/typesafehub/config

**Comment by MiniDigger** [comment]
that looks good too, don't really see how thats better than candle tho. the file format looks the same

**Comment by MiniDigger** [comment]
nope

**Comment by MiniDigger** [comment]
don't think that we need this for now. json seems fine
